start node dist/index.js
start node dist/results.js
start node dist/matchs1.js
start node dist/matchs2.js
start node dist/matchs3.js
start node dist/odds1.js
start node dist/odds2.js
start node dist/odds3.js
start node dist/ends1.js
start node dist/ends2.js
start node dist/ends3.js
start node dist/casino.js